id = "vscode-dark-modern"
name = "VSCode Dark Modern"
version = "0.0.7"
schema_version = 1
authors = ["kcamcam <kevincamellini@gmail.com>"]
description = "VSCode Dark Modern Theme for Zed"
repository = "https://github.com/kcamcam/vscode_dark_modern.zed"
